---
- hosts: all
  tags: [linux]
  tasks:
  - name: update apt
    become: yes
    apt: update_cache=yes

  - name: install apt packages
    become: yes
    apt:
      name: "{{item.name}}"
      state: latest
    with_items:
    - {name: apt-transport-https}
    - {name: build-essential}
    - {name: ca-certificates}
    - {name: ctags}
    - {name: curl}
    - {name: direnv}
    - {name: fd-find}
    - {name: neovim}
    - {name: python3-pip}
    - {name: zsh}

  - name: add Docker GPG apt Key
    become: yes
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

  - name: add Docker Repository
    become: yes
    apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu bionic stable
     state: present

  - name: update apt and install docker-ce
    become: yes
    apt: update_cache=yes name=docker-ce state=latest

  - name: update Homebrew
    homebrew: update_homebrew=yes

  - name: add Homebrew taps
    homebrew_tap: name={{item}}
    with_items:
    - git-duet/tap
    - vmware-tanzu/carvel

  - name: install Homebrew packages
    homebrew:
      name: "{{item.name}}"
      install_options: "{{item.install_options}}"
      state: latest
    with_items:
    - {name: bat, install_options: ''}
    - {name: git-duet, install_options: ''}
    - {name: go, install_options: ''}
    - {name: helm, install_options: ''}
    - {name: imgpkg, install_options: ''}
    - {name: jq, install_options: ''}
    - {name: kapp, install_options: ''}
    - {name: kbld, install_options: ''}
    - {name: kind, install_options: ''}
    - {name: ko, install_options: ''}
    - {name: krew, install_options: ''}
    - {name: kubernetes-cli, install_options: ''}
    - {name: kubectx, install_options: ''}
    - {name: kustomize, install_options: ''}
    - {name: kwt, install_options: ''}
    - {name: lastpass-cli, install_options: ''}
    - {name: libgit2, install_options: ''}
    - {name: minikube, install_options: ''}
    - {name: node, install_options: ''}
    - {name: pstree, install_options: ''}
    - {name: pure, install_options: ''}
    - {name: ripgrep, install_options: ''}
    - {name: shellcheck, install_options: ''}
    - {name: sshuttle, install_options: ''}
    - {name: stern, install_options: ''}
    - {name: tealdeer, install_options: ''}
    - {name: terraform, install_options: ''}
    - {name: tig, install_options: ''}
    - {name: tmate, install_options: ''}
    - {name: tree, install_options: ''}
    - {name: vendir, install_options: ''}
    - {name: xz, install_options: ''}
    - {name: yj, install_options: ''}
    - {name: yq, install_options: ''}
    - {name: ytt, install_options: ''}
    - {name: zsh-syntax-highlighting, install_options: ''}
    - {name: zstd, install_options: ''}
